# Basically copied from 
# https://github.com/StanfordSNR/observatory/blob/master/src/scripts/experiments.yml.
# Modified a bit for our purposes.

meta:
  branch: master
  base_dir: {src_dir}
  test_path: {src_dir}/_build/deps/pantheon/src/experiments/test.py
  data_base_dir: {src_dir}/data
  tmp_dir: {src_dir}/tmp
  install_deps_path: {pantheon_root}/tools/install_deps.sh
  pkill_path: {pantheon_root}/tools/pkill.py
  setup_system_path: {pantheon_root}/src/experiments/setup_system.py
  setup_path: {pantheon_root}/src/experiments/setup.py
  analyze_path: {pantheon_root}/src/analysis/analyze.py
  traces_dir: {src_dir}/train/traces


emu:
  macros:
    common_param_set: >-
      local --data-dir {data_dir} --pkill-cleanup
  jobs: # total_envs = 3200 + 75 + 75 + 120 + 75 = 3430
    ##########################################################################################
    - scenario: 0 # envs = 75
      desc: >-
        A training scenario
      params:
        flows: [1]
        bandwidth: ["12-x1", "24-x1", "48-x1", "96-x1", "192-x1"]
        queue: [0.5, 1, 2, 4, 8, 16]
        loss_ratio: [0, 0.0001, 0.001, 0.01, 0.05]
        delay: [1]
      command: >-
        {test_path} {common_param_set} --runtime 30 -f {flows}
        --uplink-trace {traces_dir}/wired{bandwidth}-35
        --downlink-trace {traces_dir}/wired{bandwidth}-35
        --prepend-mm-cmds "mm-delay {delay}"
        --extra-mm-link-args "--uplink-queue=droptail --uplink-queue-args=packets={queue}"
        --append-mm-cmds "mm-loss uplink {loss_ratio}"
    - scenario: 1 # envs = 120
      desc: >-
        A training scenario
      params:
        flows: [1]
        bandwidth: ["12-x2", "24-x2", "24-x0.5", "48-x2", "48-x0.5", "96-x2", "96-x0.5", "192-x0.5"]
        queue: [0.5, 1, 2, 4, 8, 16]
        loss_ratio: [0, 0.0001, 0.001, 0.01, 0.05]
        delay: [1]
      command: >-
        {test_path} {common_param_set} --runtime 30 -f {flows}
        --uplink-trace {traces_dir}/wired{bandwidth}-35
        --downlink-trace {traces_dir}/wired{bandwidth}-35
        --prepend-mm-cmds "mm-delay {delay}"
        --extra-mm-link-args "--uplink-queue=droptail --uplink-queue-args=packets={queue}"
        --append-mm-cmds "mm-loss uplink {loss_ratio}"
    - scenario: 2 # envs = 625
      desc: >-
        A training scenario
      params:
        flows: [2]
        bandwidth: ["12-x1", "24-x1", "48-x1", "96-x1", "192-x1"]
        queue: [1, 2, 4, 8, 16]
        loss_ratio: [0, 0.0001, 0.001, 0.01, 0.05]
        delay: [5, 10, 20, 40, 80]
      command: >-
        {test_path} {common_param_set} --runtime 30 -f {flows}
        --uplink-trace {traces_dir}/wired{bandwidth}-35
        --downlink-trace {traces_dir}/wired{bandwidth}-35
        --prepend-mm-cmds "mm-delay {delay}"
        --extra-mm-link-args "--uplink-queue=droptail --uplink-queue-args=packets={queue}"
        --append-mm-cmds "mm-loss uplink {loss_ratio}"
    - scenario: 3 # envs = 625
      desc: >-
        A training scenario
      params:
        flows: [3]
        bandwidth: bandwidth: ["12-x1", "24-x1", "48-x1", "96-x1", "192-x1"]
        queue: [1, 2, 4, 8, 16]
        loss_ratio: [0, 0.0001, 0.001, 0.01, 0.05]
        delay: [5, 10, 20, 40, 80]
      command: >-
        {test_path} {common_param_set} --runtime 30 -f {flows}
        --uplink-trace {traces_dir}/wired{bandwidth}-35
        --downlink-trace {traces_dir}/wired{bandwidth}-35
        --prepend-mm-cmds "mm-delay {delay}"
        --extra-mm-link-args "--uplink-queue=droptail --uplink-queue-args=packets={queue}"
        --append-mm-cmds "mm-loss uplink {loss_ratio}"